###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        container_name: mysql
        #        image: 'mysql:5.7.22'
        build: ./phpdocker/mysql
        restart: unless-stopped
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "desafio_gesuas"
            MYSQL_USER: "gesuas"
            MYSQL_PASSWORD: "gesuas"
        ports:
            - '8082:3306'
        networks:
            - gesuas

    webserver:
        container_name: nginx
        image: 'nginx:alpine'
        working_dir: /var/www/
        restart: unless-stopped
        volumes:
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'
        networks:
            - gesuas

    php-fpm:
        container_name: php-fpm
        build: phpdocker/php-fpm
        working_dir: /var/www/
        volumes:
            - '.:/var/www'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - gesuas

networks:
    gesuas:
        driver: bridge
