<!DOCTYPE html>
<html lang="<?= CONF_SITE_LANG ?>">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="<?= CONF_SITE_DESC ?>">
  <title><?= CONF_SITE_TITLE ?></title>

  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous"
  />

</head>
<body>
<header>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="text-danger"><?= CONF_SITE_NAME ?></h1>
      </div>
    </div>
  </div>
</header>

<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
  integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
  crossorigin="anonymous"
></script>
</body>
</html>
