<!DOCTYPE html>
<html lang="<?= CONF_SITE_LANG ?>">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="<?= CONF_SITE_DESC ?>">
  <title><?= CONF_SITE_TITLE ?></title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <style>
    :root {
      --font-small: 0.875em;
      --font-normal: 1em;
      --font-medium: 1.2em;
      --font-large: 1.4em;

      --color-default: #555555;
      --color-green: #36BA9B;
      --color-blue: #39AED9;
      --color-yellow: #F5B946;
      --color-red: #D94352;

      --weight-light: 300;
      --weight-normal: 400;
      --weight-bold: 700;
      --weight-black: 900;

      --hover-color-green: #61DDBC;
      --hover-color-blue: #66D4F1;
      --hover-color-yellow: #FCD277;
      --hover-color-red: #F76C82;
      --hover-duration: 0.3s;

      --gradient-green: linear-gradient(to right, #42E695 0%, #3BB2B8 50%, #42E695 100%);
      --gradient-blue: linear-gradient(to right, #17EAD9 0%, #6078EA 50%, #17EAD9 100%);
      --gradient-red: linear-gradient(to right, #622744 0%, #C53364 50%, #622744 100%);
      --gradient-yellow: linear-gradient(to right, #FCE38A 0%, #F38181 50%, #FCE38A 100%);

      --radius-normal: 5px;
      --radius-medium: 10px;
      --radius-large: 20px;
      --radius-round: 50%;

      --index-back: -1;
      --index-fold: 2;
      --index-menu: 3;
      --index-modal: 4;
    }
    .message {
      display: block;
      margin-bottom: 20px;
      padding: 15px;
      text-align: center;
      -webkit-border-radius: var(--radius-medium);
      -moz-border-radius: var(--radius-medium);
      border-radius: var(--radius-medium);
      border: 1px solid #cccccc;
      font-weight: var(--weight-bold);
    }

    .message.success {
      color: var(--color-green);
      border-color: var(--color-green);
    }
  </style>
</head>
<body>
<header>
  <div class="container">
    <?php if(flash()): ?>
      <div class="row">
        <div class="col-12">
          <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div>
              <?= flash() ?>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>
    <div class="row">
      <div class="col-12">
        <h1 class="text-info text-center"><?= CONF_SITE_NAME ?></h1>
      </div>
    </div>
  </div>
</header>
<main id="content">
  <?= $this->section('content') ?>
</main>
<footer>
<?= $this->section('footer') ?>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<?= $this->section('js') ?>
</body>
</html>
